export interface ProductionRecord {
  id: string;
  date: string;
  time: string;
  employeeId: string;
  employeeName: string;
  department: string;
  productionQuantity: number;
  machineUsed: string;
  machineIssues: boolean;
  issuesDetails: string;
  productionDelay: boolean;
  delayDetails: string;
  qualityIssueObserved: boolean;
  qualityDetails: string;
  suggestions: string;
  workingHours: number;
  safetyIssues: boolean;
  safetyDetails: string;
  materialShortage: boolean;
  materialDetails: string;
  supervisorName: string;
  supervisorFeedback: string;
  submissionStatus: "Submitted" | "Pending";
}

export interface Employee {
  id: string; // Employee ID
  name: string;
  department: string;
  email: string;
  photoUrl: string; // base64 or placeholder URL
  status: "Active" | "Inactive";
  attendance: "Present" | "Absent";
  role: string;
}

export interface AIReportSummary {
  date: string;
  totalEmployees: number;
  presentEmployees: number;
  absentEmployees: number;
  totalProduction: number;
  averageWorkingHours: number;
  machineIssuesCount: number;
  safetyIssuesCount: number;
  aiInsights: string; // Markdown text or structured suggestions generated by Gemini
  departmentSummary: {
    department: string;
    production: number;
    count: number;
    issues: number;
  }[];
}

export interface ZapierWebhookConfig {
  webhookUrl: string;
  isEnabled: boolean;
}
